logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG

wechat:
  mp:
    appId: wx8f18aee9694d50b0
    secret: 0421a7e4d0305e733d67f7a71d64f503
    token: 123456
    aesKey: SHA1
server:
  port: 8080
spring:
  datasource:
    name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-h20soudg.sql.tencentcdb.com:63095/wechat
    username: root
    password: z951837256

