spring:
  datasource:
    name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-h20soudg.sql.tencentcdb.com:63095/wechat
    username: root
    password: z951837256
  redis:
        host: 58.87.79.131
        port: 6379
        password:
        timeout: 10000
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000

logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG

wechat:
  mp:
    appId: wx3fcb154832732b75
    secret: 6961c68cc55aad7fc460a03fb08b281c
    token: l492LBlIFo2040n04mNwFBOZ0289v90l
    aesKey: SHA1
server:
  port: 8080


#mybatis
mybatis-plus:
#  mapper-locations: classpath:/com/zy/wreserve/**/*Mapper.xml
  mapper-locations: /mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zy.wreserve.wechat.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    refresh: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 单点信息配置，全部可无

kisso:
  config:
    signkey: C691d971EJ3H376G81   # 对称签名密钥
    cookieName: kisso             # COOKIE 名称

